import Head from 'next/head'
import styles from '@/styles/Dashboard.module.scss'
import { NewPostForm } from '@/components/NewPostForm';
import { NewEventForm } from '@/components/NewEventForm';
import { Events } from '@/components/Events';


const Dashboard = () => {
  return (
    <>
      <Head>
        <title>im movement - dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <section>
          <h2>Add new blog post</h2>
          <NewPostForm/>
        </section>
        <section>
            <h2>Add new event</h2>
            <NewEventForm/>
        </section>
        <section>
          <Events />
        </section>
      </main>
    </>
  )
}

export default Dashboard;