import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import hero from '../public/izzy.jpg'
import { FaInstagram, FaTiktok } from 'react-icons/fa';
import { Button } from '@/components/button'

// const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  return (
    <>
      <Head>
        <title>immovement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.mainContainer}>
          <Image
              className={styles.hero}
              src="/izzy.jpg"
              alt="Isabelle wearing all white standing under two chevron neon lights, one light is red and is one blue"
              width={1290} 
              height={1609}
              layout="responsive"
              // height={37}
              // priority
            />
          <h1 className={styles.heading}>
            immovement
          </h1>
          <h2 className={styles.subHeading}>coming soon...</h2>
          <Button title="sign up" onClick={()=>alert('sign up')} />
        </section>
        <section className={styles.social}>
          <FaInstagram color="white" />
          <FaTiktok color="white" />
        </section>
      </main>
    </>
  )
}

export default Home;